#include <stddef.h>
#include "tr2/modbus/register_model.h"

#define D(address_, block_, access_, kind_) \
    { (uint16_t)(address_), (block_), (access_), (kind_) }

static const ModbusRegisterDescriptor descriptors[] = {
    D(0, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_MSW),
    D(1, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_LSW),
    D(2, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(3, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(5, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(6, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(7, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_BITFIELD16),
    D(8, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(9, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(10, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(11, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(12, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(13, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(14, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(15, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(16, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(17, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(18, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(19, MODBUS_BLOCK_0, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(20, MODBUS_BLOCK_0, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),

    D(1000, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_ENUM16),
    D(1001, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_BITFIELD16),
    D(1002, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_BITFIELD16),
    D(1003, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_BITFIELD16),
    D(1004, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_MSW),
    D(1005, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_LSW),
    D(1006, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_ENUM16),
    D(1007, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_INT16),
    D(1008, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(1009, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(1010, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_ENUM16),
    D(1011, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(1012, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_ENUM16),
    D(1013, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_MSW),
    D(1014, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_LSW),
    D(1015, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(1016, MODBUS_BLOCK_1, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(1017, MODBUS_BLOCK_1, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(1018, MODBUS_BLOCK_1, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(1019, MODBUS_BLOCK_1, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),

    D(2000, MODBUS_BLOCK_2, MODBUS_REGISTER_RO, MODBUS_REGISTER_ENUM16),
    D(2001, MODBUS_BLOCK_2, MODBUS_REGISTER_RO, MODBUS_REGISTER_BITFIELD16),
    D(2002, MODBUS_BLOCK_2, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_MSW),
    D(2003, MODBUS_BLOCK_2, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_LSW),
    D(2004, MODBUS_BLOCK_2, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_MSW),
    D(2005, MODBUS_BLOCK_2, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_LSW),
    D(2006, MODBUS_BLOCK_2, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_MSW),
    D(2007, MODBUS_BLOCK_2, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_LSW),
    D(2008, MODBUS_BLOCK_2, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_MSW),
    D(2009, MODBUS_BLOCK_2, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_LSW),
    D(2010, MODBUS_BLOCK_2, MODBUS_REGISTER_RO, MODBUS_REGISTER_ENUM16),
    D(2011, MODBUS_BLOCK_2, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(2012, MODBUS_BLOCK_2, MODBUS_REGISTER_RO, MODBUS_REGISTER_INT16),
    D(2013, MODBUS_BLOCK_2, MODBUS_REGISTER_RO, MODBUS_REGISTER_ENUM16),
    D(2014, MODBUS_BLOCK_2, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(2015, MODBUS_BLOCK_2, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),

    D(4000, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4001, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_BITFIELD16),
    D(4002, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_MSW),
    D(4003, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_LSW),
    D(4004, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_MSW),
    D(4005, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_LSW),
    D(4006, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ENUM16),
    D(4007, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4008, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_MSW),
    D(4009, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_LSW),
    D(4010, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_MSW),
    D(4011, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_LSW),
    D(4012, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_MSW),
    D(4013, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_LSW),
    D(4014, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4015, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),

    D(4016, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT16),
    D(4017, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4018, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_BITFIELD16),
    D(4019, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ENUM16),
    D(4020, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ENUM16),
    D(4021, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT16),
    D(4022, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT16),
    D(4023, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_MSW),
    D(4024, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_LSW),
    D(4025, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ENUM16),
    D(4026, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_MSW),
    D(4027, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_LSW),
    D(4028, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4029, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4030, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4031, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4032, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4033, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4034, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4035, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4036, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4037, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4038, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4039, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),

    D(4040, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_BITFIELD16),
    D(4041, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT16),
    D(4042, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT16),
    D(4043, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT16),
    D(4044, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT16),
    D(4045, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT16),
    D(4046, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT16),
    D(4047, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4048, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4049, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4050, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4051, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4052, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4053, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4054, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4055, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),

    D(4056, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_MSW),
    D(4057, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_LSW),
    D(4058, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_MSW),
    D(4059, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT32_LSW),
    D(4060, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4061, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4062, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4063, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4064, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4065, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4066, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4067, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4068, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4069, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4070, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4071, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4072, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4073, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4074, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4075, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4076, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4077, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4078, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4079, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4080, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4081, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4082, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4083, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4084, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4085, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4086, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4087, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4088, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4089, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4090, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4091, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_ASCII),
    D(4092, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT16),
    D(4093, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT16),
    D(4094, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT16),
    D(4095, MODBUS_BLOCK_4, MODBUS_REGISTER_RW, MODBUS_REGISTER_UINT16),
    D(4096, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4097, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4098, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4099, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),

    D(4100, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4101, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_BITFIELD16),
    D(4102, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ENUM16),
    D(4103, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ENUM16),
    D(4104, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4105, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4106, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_MSW),
    D(4107, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_LSW),
    D(4108, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ENUM16),
    D(4109, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_MSW),
    D(4110, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_LSW),
    D(4111, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4112, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4113, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4114, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4115, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4116, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_BITFIELD16),
    D(4117, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4118, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4119, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4120, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4121, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4122, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4123, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4124, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4125, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4126, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4127, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4128, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_MSW),
    D(4129, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_LSW),
    D(4130, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_MSW),
    D(4131, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT32_LSW),
    D(4132, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4133, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4134, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4135, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4136, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4137, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4138, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4139, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4140, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4141, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4142, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4143, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4144, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4145, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4146, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4147, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4148, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4149, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4150, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4151, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4152, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4153, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4154, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4155, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4156, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4157, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4158, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4159, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4160, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4161, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4162, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4163, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_ASCII),
    D(4164, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4165, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4166, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4167, MODBUS_BLOCK_4, MODBUS_REGISTER_RO, MODBUS_REGISTER_UINT16),
    D(4168, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4169, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4170, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4171, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4172, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4173, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4174, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
    D(4175, MODBUS_BLOCK_4, MODBUS_REGISTER_RESERVED, MODBUS_REGISTER_UINT16),
};

#undef D

static size_t descriptor_count(void)
{
    return sizeof(descriptors) / sizeof(descriptors[0]);
}

bool modbus_register_descriptor_is_valid(const ModbusRegisterDescriptor *descriptor)
{
    if (descriptor == NULL) {
        return false;
    }

    if (descriptor->block < MODBUS_BLOCK_0 || descriptor->block > MODBUS_BLOCK_7) {
        return false;
    }

    if (descriptor->access < MODBUS_REGISTER_RO || descriptor->access > MODBUS_REGISTER_RESERVED) {
        return false;
    }

    return descriptor->kind >= MODBUS_REGISTER_UINT16 &&
           descriptor->kind <= MODBUS_REGISTER_ASCII;
}

bool modbus_register_is_writable(const ModbusRegisterDescriptor *descriptor)
{
    return modbus_register_descriptor_is_valid(descriptor) &&
           descriptor->access == MODBUS_REGISTER_RW;
}

const ModbusRegisterDescriptor *modbus_register_model_find(uint16_t address)
{
    size_t index;

    for (index = 0u; index < descriptor_count(); ++index) {
        if (descriptors[index].address == address) {
            return &descriptors[index];
        }
    }

    return NULL;
}

bool modbus_register_model_range_exists(uint16_t start_address, uint16_t quantity)
{
    uint32_t offset;

    if (quantity == 0u) {
        return false;
    }

    for (offset = 0u; offset < (uint32_t)quantity; ++offset) {
        const uint32_t address = (uint32_t)start_address + offset;
        if (address > UINT16_MAX || modbus_register_model_find((uint16_t)address) == NULL) {
            return false;
        }
    }

    return true;
}

ModbusAccessResult modbus_register_model_validate_read(uint16_t start_address, uint16_t quantity)
{
    return modbus_register_model_range_exists(start_address, quantity)
               ? MODBUS_ACCESS_OK
               : MODBUS_ACCESS_ILLEGAL_ADDRESS;
}

ModbusAccessResult modbus_register_model_validate_write(uint16_t start_address, uint16_t quantity)
{
    uint32_t offset;

    if (quantity == 0u) {
        return MODBUS_ACCESS_ILLEGAL_ADDRESS;
    }

    for (offset = 0u; offset < (uint32_t)quantity; ++offset) {
        const uint32_t address = (uint32_t)start_address + offset;
        const ModbusRegisterDescriptor *descriptor;

        if (address > UINT16_MAX) {
            return MODBUS_ACCESS_ILLEGAL_ADDRESS;
        }

        descriptor = modbus_register_model_find((uint16_t)address);
        if (descriptor == NULL) {
            return MODBUS_ACCESS_ILLEGAL_ADDRESS;
        }
        if (descriptor->access == MODBUS_REGISTER_RESERVED) {
            return MODBUS_ACCESS_RESERVED;
        }
        if (descriptor->access != MODBUS_REGISTER_RW) {
            return MODBUS_ACCESS_READ_ONLY;
        }
    }

    return MODBUS_ACCESS_OK;
}
